title: John Wu's Blog
subtitle: 簡單不想寫，太難不會寫。
description: >-
  正在培養寫技術部落格的 Web 工程師，擅長 ASP .NET MVC / Web API 2、.NET Core、Angular 網站開發，也略懂 ELK
  stack 及 Jenkins 應用。目前正在學習敏捷軟體開發及 Scrum。
author: John Wu
language: default
timezone: Asia/Taipei
avatar: /images/avatar.png
favicon: /favicon.ico
icon: /images/icon.png
lang_code: zh-Hant
keywords: >-
  John Wu's Blog,ASP.NET Core,ASP.NET MVC,ASP.NET Web API 2,Angular,Angular
  2,Angular 4,jQuery,C#,JavaScript,TypeScript,Jenkins,groovy
domain: blog.johnwu.cc
url: https://blog.johnwu.cc
root: /
permalink: article/:title.html
permalink_defaults: null
source_dir: source
public_dir: artifacts
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: draft
titlecase: false
external_link.enable: true
filename_case: 1
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: '  '
default_category: uncategorized
category_map: null
tag_map: null
date_format: YYYY-MM-DD
time_format: HH:mm:ss
per_page: 10
pagination_dir: page
theme: material-flow
social:
  - slug: github
    url: https://github.com/johnwu1114
  - slug: linkedin
    url: https://www.linkedin.com/in/johnwu1114
  - slug: rss
    url: /atom.xml
pageviews_api: https://asia-east2-blog-johnwu-cc.cloudfunctions.net/page-views
disqus_shortname: blog-johnwu-cc
google_translate: false
google_custom_search: true
facebook_sdk:
  enable: true
  like_button: true
  webmaster: true
  app_id: '1046791958755149'
  fb_admin: '972414696145753'
marked:
  breaks: false
sitemap:
  path: sitemap.xml
nofollow:
  enable: true
  exclude:
    - github.com
    - mvp.microsoft.com
    - www.youracclaim.com
    - ithelp.ithome.com.tw
    - blackie1019.github.io
    - larrynung.github.io
    - blog.yowko.com
    - medium.com
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub: null
html_minifier:
  enable: true
  ignore_error: false
  exclude: null
css_minifier:
  enable: true
  exclude:
    - '*.min.css'
js_minifier:
  enable: true
  mangle: true
  exclude:
    - '*.min.js'
image_minifier:
  enable: true
  interlaced: true
  multipass: true
  optimizationLevel: 4
  pngquant: true
  progressive: true
awards_certs:
  - title: Microsoft MVP 2018-2020
    url: https://mvp.microsoft.com/zh-tw/PublicProfile/5002961
    image: /images/mvp.png
    width: 180
    summary: Visual Studio and Development Technologies
  - title: null
    url: >-
      https://www.youracclaim.com/badges/e5266cbb-d375-4807-aa75-f0da5e2f9966/public_url
    image: /images/MCSA-WebApps.png
    image_alt: 'MCSA: Web Applications - Certified 2016'
    width: 120
  - title: null
    url: >-
      https://www.youracclaim.com/badges/ac1a0583-4534-4a15-ab7e-0b068d80bd23/public_url
    image: /images/MCSD-AppBuilder.png
    image_alt: 'MCSD: App Builder - Certified 2016'
    width: 120
  - title: null
    url: https://ithelp.ithome.com.tw/users/20107461/ironman/1372
    image: /images/ironman-2018-modern-web.png
    image_alt: 2018 iT 邦幫忙鐵人賽 - ASP.NET Core 從入門到實用
    width: 100
links:
  - name: 吳吉米 - YouTube 技術頻道
    url: https://www.youtube.com/user/02047788a
  - name: Blackie - Failed Notes
    url: https://blackie1019.github.io/
  - name: Larry - Level up
    url: https://larrynung.github.io/
  - name: Yowko - Yowko's Notes
    url: https://blog.yowko.com/
google_analytics: <GOOGLE_ANALYTICS_ID>
google_analytics_v4: G-NSKXB3JS7L
